server.port=8080

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-wispy-base-a4ajmkwb-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_q8okbGayip9U}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
